@baseUrl = http://localhost:3050/v1

### Route GET /boardgames
GET {{baseUrl}}/boardgames

### Route GET /boardgames/:id
GET {{baseUrl}}/boardgames/1

### Route POST /boardgames
POST {{baseUrl}}//boardgames
Content-Type: application/json

{
    "name": "Dixit",
    "minAge": "8",
    "minPlayers": "3",
    "maxPlayers": "6",
    "type": "créativité",
    "note": "5",
    "duration": "60",
    "creator": "Jean-Louis Roubira"
}

### ! Route POST /boardgames avec ERREURS (test de la validation Joi)
POST {{baseUrl}}//boardgames
Content-Type: application/json

{
    "name": "Cluedo",
    "minAge": "8",
    "minPlayers": "3",
    "maxPlayers": "6",
    "type": "déduction",
    "note": "4",
    "duration": "20 minutes",
    "creator": "Anthony Pratt"
}

