@baseUrl = http://localhost:3050/v1

### Route GET /boardgames
GET {{baseUrl}}/boardgames

### Route GET /boardgames/:id
GET {{baseUrl}}/boardgames/6

### Route GET /boardgames/:id AVEC ERREUR - mauvais numéro
GET {{baseUrl}}/boardgames/12

### Route GET /boardgames/:id AVEC ERREUR - mauvais type 
GET {{baseUrl}}/boardgames/test

### Route POST /boardgames
POST {{baseUrl}}//boardgames
Content-Type: application/json

{
    "name": "Dixit",
    "minAge": "8",
    "minPlayers": "4",
    "maxPlayers": "6",
    "type": "créativité",
    "note": "5",
    "duration": "60",
    "creator": "Jean-Louis Roubira"
}

### ! Route POST /boardgames avec ERREURS (test de la validation Joi)
POST {{baseUrl}}//boardgames
Content-Type: application/json

{
    "name": "Cluedo",
    "minAge": "8",
    "minPlayers": "4",
    "maxPlayers": "6",
    "note": "4",
    "duration": "20 minutes",
    "creator": "Anthony Pratt"
}

### Route DELETE /boardgames/:id
DELETE {{baseUrl}}//boardgames/27

### Route PATCH /boardgames/:id
PATCH {{baseUrl}}//boardgames/6
Content-Type: application/json

{
    "name": "Cluedo",
    "minAge": "8",
    "minPlayers": "5",
    "maxPlayers": "6",
    "type": "déduction",
    "note": "4",
    "duration": "20",
    "creator": "Anthony Pratt"
}

### Route PATCH /boardgames/:id
PATCH {{baseUrl}}//boardgames/6
Content-Type: application/json

{
    "minAge": "10",
    "note": "4",
    "duration": "60",
    "creator": "test"
}
